const state={references:[],pages:[],selected:null,pdfPages:[]};
const examples=[{src:'assets/exemplo-da-anotacao_pages-to-jpg-0001.jpg',name:'Exemplo 1'},{src:'assets/ChatGPT-Image-15-de-set.-de-2026-18_29_45.jpg',name:'Alfabeto e números'},{src:'assets/exemplo-da-anotacao_pages-to-jpg-0002.jpg',name:'Exemplo 2'}];
const $=id=>document.getElementById(id);
function makeImage(src,alt){const img=new Image();img.src=src;img.alt=alt;return img}
function renderReferences(){const box=$('reference-gallery');box.innerHTML='';[...examples,...state.references].forEach((item,i)=>{const fig=document.createElement('figure');fig.className='reference-card';const img=makeImage(item.src,item.name||`Referência ${i+1}`);img.addEventListener('click',()=>openLightbox(item.src,img.alt));fig.append(img);const cap=document.createElement('figcaption');cap.textContent=item.name||`Imagem adicionada ${i+1}`;fig.append(cap);box.append(fig)})}
function openLightbox(src,alt){const d=document.createElement('dialog');d.className='lightbox';d.innerHTML=`<button aria-label="Fechar">×</button><img src="${src}" alt="${alt}">`;document.body.append(d);d.showModal();d.querySelector('button').onclick=()=>{d.close();d.remove()};d.addEventListener('click',e=>{if(e.target===d){d.close();d.remove()}})}
function fileData(file){return new Promise((resolve,reject)=>{const r=new FileReader();r.onload=()=>resolve({src:r.result,name:file.name});r.onerror=reject;r.readAsDataURL(file)})}
$('reference-input').addEventListener('change',async e=>{for(const f of e.target.files)state.references.push(await fileData(f));renderReferences()});
function renderPages(){const grid=$('page-grid');grid.innerHTML='';$('empty-state').style.display=state.pages.length?'none':'grid';state.pages.forEach((p,i)=>{const card=document.createElement('div');card.className='page '+(state.selected===i?'selected':'');card.onclick=()=>{state.selected=i;renderPages();syncAdjustments()};const img=makeImage(p.src,`Página ${i+1}`);img.style.filter=`brightness(${p.brightness}%) contrast(${p.contrast}%)`;card.append(img);const n=document.createElement('span');n.className='page-number';n.textContent=`Página ${i+1} · arraste para selecionar`;card.append(n);grid.append(card)})}
async function addPages(files){for(const f of files)state.pages.push({...await fileData(f),brightness:100,contrast:100,rotation:0});if(state.selected===null&&state.pages.length)state.selected=0;renderPages();syncAdjustments()}
$('gallery-input-button').onclick=()=>$('gallery-input').click();$('gallery-input').addEventListener('change',e=>addPages([...e.target.files]));$('camera-open').onclick=()=>$('camera-input').click();$('camera-input').addEventListener('change',e=>addPages([...e.target.files]));
function syncAdjustments(){const p=state.pages[state.selected];if(!p)return;$('brightness').value=p.brightness;$('contrast').value=p.contrast}
['brightness','contrast'].forEach(id=>$(id).addEventListener('input',e=>{const p=state.pages[state.selected];if(!p)return;p[id]=e.target.value;renderPages()}));$('rotate-left').onclick=()=>{const p=state.pages[state.selected];if(!p)return;p.rotation=(p.rotation+270)%360;renderPages()};$('delete-page').onclick=()=>{if(state.selected===null)return;state.pages.splice(state.selected,1);state.selected=state.pages.length?Math.min(state.selected,state.pages.length-1):null;renderPages()});
function previewPDF(items){const box=$('pdf-preview');box.innerHTML='';items.forEach(p=>{const img=makeImage(p.src,p.name||'Página');img.style.filter=`brightness(${p.brightness||100}%) contrast(${p.contrast||100}%)`;img.style.transform=`rotate(${p.rotation||0}deg)`;box.append(img)});$('preview-dialog').showModal()}
$('scanner-pdf').onclick=()=>{if(!state.pages.length){$('scanner-status').textContent='Adicione pelo menos uma página.';return}state.pdfPages=state.pages.map(p=>({...p}));previewPDF(state.pdfPages);$('scanner-status').textContent=''};
$('reference-pdf').onclick=()=>{const items=[...examples,...state.references];if(!items.length){$('reference-status').textContent='Adicione imagens de referência.';return}state.pdfPages=items.map(x=>({...x}));previewPDF(state.pdfPages);$('reference-status').textContent=''};
$('close-dialog').onclick=()=>$('preview-dialog').close();$('cancel-pdf').onclick=()=>$('preview-dialog').close();
$('download-pdf').onclick=async()=>{if(!state.pdfPages.length)return;$('download-pdf').textContent='Preparando...';try{await loadPdfLib();const {jsPDF}=window.jspdf;const pdf=new jsPDF({unit:'px',format:'a4'});for(let i=0;i<state.pdfPages.length;i++){const p=state.pdfPages[i],img=await loadImg(p.src);if(i)pdf.addPage('a4','p');const pw=pdf.internal.pageSize.getWidth(),ph=pdf.internal.pageSize.getHeight(),s=Math.min(pw/img.width,ph/img.height),w=img.width*s,h=img.height*s;pdf.addImage(img,'JPEG',(pw-w)/2,(ph-h)/2,w,h)}pdf.save('test-maker-documento.pdf')}catch(e){alert('Não foi possível criar o PDF: '+e.message)}finally{$('download-pdf').textContent='Baixar PDF'}};
function loadPdfLib(){return new Promise((resolve,reject)=>{if(window.jspdf)return resolve();const s=document.createElement('script');s.src='https://cdnjs.cloudflare.com/ajax/libs/jspdf/2.5.1/jspdf.umd.min.js';s.onload=resolve;s.onerror=reject;document.head.append(s)})}function loadImg(src){return new Promise((resolve,reject)=>{const i=new Image();i.onload=()=>resolve(i);i.onerror=reject;i.src=src})}
renderReferences();